language: go

go:
  - 1.5
  - 1.6
  - tip

install:
  - go get github.com/Masterminds/glide
  - ${GOPATH}/bin/glide install

allow_failures:
  - go: tip

script:
  - go build
  - go test -v ./
  - "! gofmt -l $(find . -path ./vendor -prune -o -name '*.go' -print) | read nothing"

env:
  - "GO15VENDOREXPERIMENT=1"
